insert into rooms (id, overview_vg_id, detail_vg_id, num , x_pos , y_pos) values (1,1,1,0,0,0);
insert into rooms (id, overview_vg_id, detail_vg_id, num , x_pos , y_pos) values (2,1,1,1,1,0);
insert into rooms (id, overview_vg_id, detail_vg_id, num , x_pos , y_pos) values (3,1,1,2,2,0);
insert into rooms (id, overview_vg_id, detail_vg_id, num , x_pos , y_pos) values (4,1,1,3,0,1);
insert into rooms (id, overview_vg_id, detail_vg_id, num , x_pos , y_pos) values (5,1,1,4,1,1);
insert into rooms (id, overview_vg_id, detail_vg_id, num , x_pos , y_pos) values (6,1,1,5,2,1);
insert into rooms (id, overview_vg_id, detail_vg_id, num , x_pos , y_pos) values (7,1,1,6,0,2);
insert into rooms (id, overview_vg_id, detail_vg_id, num , x_pos , y_pos) values (8,1,1,7,1,2);
insert into rooms (id, overview_vg_id, detail_vg_id, num , x_pos , y_pos) values (9,1,1,8,2,2);
commit;